apiVersion: v1
kind: Secret
metadata:
  name: headlamp
  namespace: system
  annotations:
    kubernetes.io/service-account.name: headlamp
    kubernetes.io/service-account.namespace: system
type: kubernetes.io/service-account-token
