apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: app-template
    version: 4.6.2
    repo: https://bjw-s-labs.github.io/helm-charts
    releaseName: ollama
    namespace: developer
    valuesFile: values.yaml
resources:
  - api
  - pvc.yaml
